export const hotelCrausel = [
    'https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/10519707/fd1e2655ac7c11e99e4f0a8e1b1ce4da_watermarked_image_1024.jpeg',
    'https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/10519707/fcaf8079ac7c11e99e4f0a8e1b1ce4da_watermarked_image_1024.jpeg',
    "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/10519707/f60594b1ac7c11e99e4f0a8e1b1ce4da_watermarked_image_1024.jpeg",
    "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/10519707/da693d11ac7c11e99e4f0a8e1b1ce4da_watermarked_image_1024.jpeg",
]

export const KEY_AMENITIES = ['POWER BACKUP', 'SHOPPING CLOSE BY', 'MICROWAVE', 'POOL / SNOOKER TABLE', 'BUZZER / INTERCOM',
'HEATING','SAFE LOCKER/DEPOSIT BOX','TABLE TENNIS','TOASTER','GAS/STOVE','REFRIGERATOR','TELEVISION','SATELLITE/CABLE CONNECTION','COMPLIMENTART NEWSPAPER','DOCTOR ON CALL','PICK AND DROP FACILITY','TRAVEL DESK','LAUNDRY & DRY CLEANING SERVICE','ROOM SERVICE','MINIBAR & GOURMET CORNER','PROJECTOR WITH SCREEN','KIDS POOL','GARDEN/LAWN','BROADBAND','BUS STOP CLOSE BY','LINEN PROVIDED','HOT WATER','WESTERN TOILET','KETTLE','SHOWER','PARKING SPACE','HOUSEKEEPING','RESTAURANTS CLOSE BY','FAN','AIR CONDITIONING','WIRELESS INTERNET','SWIMMING POOL','DECKS WITH SUNBEDS','BEACH NEARBY','BAR.B.Q GRILL','HAIR DRYER','MASSAGES','BAR','24/7 POWER','TOILETRIES']

export const BEDROOM1 = ['TELEVISION WITH CABLE CONNECTION','AC','WARDROBE','TV WITH USB','TV WITH HDMI','1 QUEEN BED(S)']

export const BEDROOM2 = ['WESTERN TOILET','CEILING SHOWER','TOILET PAPER','TOILETRIES'];

export const BESTFOR = ['BEACH VACATION','BEACH','LAKEVIEW','BUDGET STAY'];

export const PRIVATE_ROOM_ETC = ['PRIVATE ROOM','3 MAX GUESTS','WIFI','SWIMMING POOL','AC','PARKING SPACE','CARETAKER']