export const about_header_top = `CoZyTrip is one of Asia's largest Holiday Home Rental Companies. The company was founded in late 2009 by Roshan D'Silva when looking for ways to generate additional income from Coffee Plantations owned by his family in India. Inspired by Craigslist, Roshan set out to create a simple website where owners of private homes could create a simple profile for their property and then correspond with like minded families who would be interested in staying in their homes as an alternate to hotels.`
export const about_header_middle1 = `Over the years, CoZyTrip has grown to add to it's core rental business other key businesses to serve the Holiday Home industry in Asia. These include a Software business, a Vacation Community Management Business, Property Management including brokerage and Interiors of Vacation Homes, Branded development of Vacation Communities and an Exchange Program where Holiday Home owners can exchange their unsold nights with other Owners.`
export const about_header_middle2 = `CoZyTrip is headquartered in Singapore and has entered new businesses over the years to move the Holiday Home industry in Asia forward in tune with the needs and wants of consumers and Property Investors. We are passionate about the industry and about it's importance to families as they look to spend more time with each other. We are also very conscious of our social responsibility - and work closely with multiple stakeholders to balance generation of wealth for Asian families by income producing properties while protecting the local Art, Culture, Tribes, Cuisine and Wildlife. Without the uniqueness of Asia, we believe there would be nothing to see and hence our very existence would be at threat.`

export const about_header_bottom = `CoZyTrip is backed by some of the world's leading Angel groups and Funds. Our Founder and the Management team are Majority owners and are fully aligned with the success of the business.`

export const investor_NRF =`A part of the Singapore Prime Minister's office, The National Research Foundation (NRF) seeks to strengthen Singapore’s R&D capabilities, encourage greater innovation and nurture the growth of technology-based enterprises in Singapore. This will help Singapore to remain competitive and create high value jobs and prosperity for Singaporeans.`

export const investor_Labs =`Neoteny Labs is an early stage fund led by Joi Ito and advised by Reid Hoffman. Joichi "Joi" Ito is an early pioneer on the Internet and is also presently the director of MIT's Media Lab. He was the founder of one of the first commercial ISPs in Japan (sold to Cable and Wireless), one of the founders of Infoseeek Japan (sold to Disney and then Rakuten) and founder of Digital Garage (now listed on the Tokyo Stock Exchange and one of the largest Internet companies in Japan). Joi is also an international advisor to Twitter and is on the board of the New York Times and a trustee of the Knight Foundation. James Chan - a key part of the Singapore technology ecosystem and presently founder of Silicon Straits is also associated with our company through Neoteny Labs - his earlier employer.`

export const investor_blume_ventures =`Blume Ventures is one of the leading Early stage funds in India. Founded by Karthik Reddy and Sanjay Nath, Blume is one of the most influential investors in early stage consumer companies in India. The "Blume Ecosystem" comprises of the founders of over 50 early stage companies in India, advisors and mentors across the globe and Limited Partners who are also engaged with individual portfolio companies.`

export const investor_MENA_ventures =`MENA Ventures is the leading early stage fund in the Middle East and North Africa. Run by Fadi Ghandour and Walid Faza, MENA has been the investor in most important consumer internet businesses in the Middle East. Fadi Ghandour has notably been one of the founders and early backers of Maktoob - which then became Yahoo Arabia and also the founder of Aramex - a very innovative logistics company which does a lot of work to support e-commerce ventures globally.`


export const investor_limKah = `Mr. Lim is the founder of SIS international Holdings - listed on the Hong Kong Stock Exchange and one of the early pioneers of the Technology and Technology Publishing Industries in Asia. His career over the past 30 years has seen him found, build and exit some of the largest IT distribution businesses in Asia and also build some of the largest IT Media groups. His expertise across Real Estate, Publishing and doing business across Asia is very valuable to our company.`

export const investor_samer = `Samer Mouasher was born on July 19, 1971 in Amman, Jordan, to Anis Mouasher and Louly Hanania. His passion for presenting the “real” Middle East together with its rich history, culture, and nature to the world, led him to establishing several companies and non profits in the fields of the sustainability and green energy, hospitality and tourism, real estate multiuse development, technology, Cosmetics and entertainment. Samer spends most of his time between LA, London, Shanghai and Amman. In 1992, Samer graduated from Northwestern University with Majors in Political Science, Photography and Economics. His Directorships include the Royal Film Commission of Jordan, Royal Jordanian Airlines, Royal Wings Airlines, Saraya Holdings (including many Saraya Ventures), Saraya Aqaba, Gulf Circle Tours, Bespoke Hideaways and Bedu Eco Lodges, Jordan Heritage Revival Company among others.`

export const investor_otherAngles = `Our other Angels include individuals, friends and family all of whom are closely associated with the company.`
